API_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjFjNTNiMjAtMDFhNS00ZjNkLWI0ZGQtYWYzZmRiMTNhZDQ1IiwidHlwZSI6ImFwaV90b2tlbiJ9.jsUpcIHEwxuIDMYL07yQV8rZBqWm3xnN0PmCKc5I_hU"
URL = "https://api.edenai.run/v2/audio/text_to_speech"
PROVIDERS = "elevenlabs"
LANGUAGE = "en-US"
OPTION = "FEMALE"
FALLBACK_PROVIDERS = "amazon"
